import axios from 'axios';
import Head from 'next/head';
import Features from '../components/Features/Features';
import Footer from '../components/Footer/Footer';
import Header from '../components/Header/Header';
import LovelyHomeDetail from '../components/lovelyHomeDetail/LovelyHomeDetail';
import Navbar from '../components/Navbar/Navbar';
import Newsletter from '../components/Newsletter/Newsletter';
import SpecialServices from '../components/SpecialServices/SpecialServices';
import WhyUs from '../components/WhyUs/WhyUs';
import styles from '../styles/index.module.scss';

export default function Home({propertyList, homesDetails}) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Rooms - Find your hotel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/home_icon-icons.com_73532.ico" />
            </Head>

            <main className={styles.main}>
                <Navbar />
                <Header />
                <Features />
                <LovelyHomeDetail homesDetails={homesDetails} />
                {/* <Propertys propertyList2={propertyList2} /> */}
                <WhyUs />
                <SpecialServices />
                {/* <BlogComponent blogDetail={blogss} title="Rooms Blogs" /> */}
                <Newsletter />
                <Footer />
            </main>
        </div>
    );
}

export async function getStaticProps() {
    const response2 = await axios.get(
        'http://localhost:3001/api/rooms'
    );
    const data2 = await response2.data.data;

    return {
        props: {
            propertyList: data2 || null,
            homesDetails: data2 || null,
        },
    };
}
